Generating G_24

In [1]:
import numpy as np
import scipy as sp
import itertools as it
# Generating the Golay code
# First we need to define the Generator matrix
I = np.identity((12),dtype=int)
A = np.array(
[[1,0,0,1,1,1,1,1,0,0,0,1],
[0,1,0,0,1,1,1,1,1,0,1,0],
[0,0,1,0,0,1,1,1,1,1,0,1],
[1,0,0,1,0,0,1,1,1,1,1,0],
[1,1,0,0,1,0,0,1,1,1,0,1],
[1,1,1,0,0,1,0,0,1,1,1,0],
[1,1,1,1,0,0,1,0,0,1,0,1],
[1,1,1,1,1,0,0,1,0,0,1,0],
[0,1,1,1,1,1,0,0,1,0,0,1],
[0,0,1,1,1,1,1,0,0,1,1,0],
[0,1,0,1,0,1,0,1,0,1,1,1],
[1,0,1,0,1,0,1,0,1,0,1,1]])

#G is the generator matrix for G_24
G = np.block([I,A])

## Constructing all elements in the field F_{2}^n
def generate_binary_arrays(n):
    if n == 0:
        return [[]]
    else:
        prev_array = generate_binary_arrays(n-1)
        new_array = []
        for array in prev_array:
            new_array.append(array + [0])
            new_array.append(array + [1])
        return new_array

#Here we generate every element of G_24 by multiplying all elements in F_{2}^n by G

F12 = np.array(generate_binary_arrays(12))
for i in range(2**12):
  row = F12[i,:]
  c = np.matmul(row,G) % 2
  print(c)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 1 0 1 0 1 0 1 1]
[0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 1 0 1 1 1]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0]
[0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 1 1 1 0 0 1 1 0]
[0 0 0 0 0 0 0 0 0 1 0 1 1 0 0 1 0 1 0 0 1 1 0 1]
[0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 0 1 0 1 1 0 0 0 1]
[0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 1 1 0 1 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 1 1 1 0 0 1 0 0 1]
[0 0 0 0 0 0 0 0 1 0 0 1 1 1 0 1 0 1 1 0 0 0 1 0]
[0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 1 0 0 1 1 1 1 0]
[0 0 0 0 0 0 0 0 1 0 1 1 1 0 0 0 0 0 1 1 0 1 0 1]
[0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0 1 0 1 1 1 1]
[0 0 0 0 0 0 0 0 1 1 0 1 1 1 1 0 1 0 0 0 0 1 0 0]
[0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 1 0 1 1 1 1 0 0 0]
[0 0 0 0 0 0 0 0 1 1 1 1 1 0 1 1 1 1 0 1 0 0 1 1]
[0 0 0 0 0 0 0 1 0 0 0 0 1 1 1 1 1 0 0 1 0 0 1 0]
[0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 1 0 0 1 1 1 0 0 1]
[0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 1 1 0 0 0 1 0 1]
[0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 1 1 0 1 1 1 0]


checking minimal distance

In [2]:
import numpy as np
import scipy as sp
import itertools as it
#We want to find the minimum distance of G_23
G = np.array([[1,0,1,0,1,1,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0],[
0,1,0,1,0,1,1,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0],[
0,0,1,0,1,0,1,1,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0],[
0,0,0,1,0,1,0,1,1,1,0,0,0,1,1,0,0,0,0,0,0,0,0],[
0,0,0,0,1,0,1,0,1,1,1,0,0,0,1,1,0,0,0,0,0,0,0],[
0,0,0,0,0,1,0,1,0,1,1,1,0,0,0,1,1,0,0,0,0,0,0],[
0,0,0,0,0,0,1,0,1,0,1,1,1,0,0,0,1,1,0,0,0,0,0],[
0,0,0,0,0,0,0,1,0,1,0,1,1,1,0,0,0,1,1,0,0,0,0],[
0,0,0,0,0,0,0,0,1,0,1,0,1,1,1,0,0,0,1,1,0,0,0],[
0,0,0,0,0,0,0,0,0,1,0,1,0,1,1,1,0,0,0,1,1,0,0],[
0,0,0,0,0,0,0,0,0,0,1,0,1,0,1,1,1,0,0,0,1,1,0],[
0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,1,1,1,0,0,0,1,1]])

## Constructing all elements in the field F_{2}^n
def generate_binary_arrays(n):
    if n == 0:
        return [[]]
    else:
        prev_array = generate_binary_arrays(n-1)
        new_array = []
        for array in prev_array:
            new_array.append(array + [0])
            new_array.append(array + [1])
        return new_array

#We initialize counts to keep track of the minimal distance of each element in G_23
counts = {}

F12 = np.array(generate_binary_arrays(12))

#Here we generate G_23 and save their hamming weights in counters as a tally
for i in range(2**12):
  row = F12[i,:]
  c = np.matmul(row,G) % 2
  d = np.sum(c)
  if d in counts:
        counts[d] += 1
  else:
        counts[d] = 1
print(counts)

##From he output we clearly see that d=7 as the lowest non-zero hamming weight is 7

{0: 1, 7: 253, 8: 506, 12: 1288, 11: 1288, 15: 506, 16: 253, 23: 1}
